package com.example.ui

object Localization {
    
    fun get(key: String, language: AppLanguage): String {
        val dict = if (language == AppLanguage.AR) arDict else enDict
        return dict[key] ?: key
    }

    private val enDict = mapOf(
        "app_title" to "Campus Parking Hub",
        "app_subtitle" to "Real-time Smart Parking Management",
        "role_user" to "Student / Staff",
        "role_security" to "Security Office",
        "select_lang" to "العربية",
        "active_user" to "Active Driver Profile",
        "current_zone" to "Selected Zone",
        "free_slots" to "Available Slots",
        "total_slots" to "Total Capacity",
        "reserve_now" to "Reserve This Slot",
        "reservation_title" to "Quick Reservation",
        "select_vehicle" to "Select Vehicle",
        "input_vehicle_plate" to "Enter License Plate (e.g. KSA-1234)",
        "duration" to "Duration",
        "hours" to "Hours",
        "confirm_reservation" to "Confirm Reservation",
        "cancel" to "Cancel",
        "active_reservations_label" to "Your Active Reservations",
        "expiry_time" to "Expires",
        "extend_time" to "Extend Time",
        "payment_status" to "Payment Status",
        "is_paid" to "Paid",
        "unpaid" to "Unpaid (Pay Now)",
        "pay_now" to "Pay Parking Fee",
        "permit_status" to "Your Parking Permits",
        "apply_permit" to "Apply for Campus Permit",
        "vehicle_model" to "Vehicle Model",
        "permit_type" to "Permit Duration",
        "permit_student" to "Student Semester Permit ($100)",
        "permit_staff" to "Staff Annual Permit ($200)",
        "permit_visitor" to "Visitor Daily Pass ($10)",
        "register_and_apply" to "Apply & Register Vehicle",
        "history_label" to "Parking & Payment History",
        "method" to "Method",
        "amount" to "Amount",
        "time" to "Time",
        "receipt" to "Receipt",
        
        // Security side
        "security_monitoring" to "Real-time Campus Occupancy",
        "occupancy_rate" to "System Occupancy Rate",
        "registered_violations" to "Active Campus Violations",
        "issue_violation" to "Issue Parking Citation",
        "violation_type" to "Violation Type",
        "fine_amount" to "Fine Amount",
        "location" to "Location",
        "notes" to "Additional Notes",
        "issue_citation_btn" to "Issue Ticket",
        "violation_history" to "Citation Records",
        "verified_permits" to "Registered Campus Permits",
        "check_in_out" to "Gate Registrar (Entry/Exit)",
        "license_plate_label" to "License Plate",
        "check_in_btn" to "Register Check-In",
        "check_out_btn" to "Register Check-Out",
        "generate_report_btn" to "Generate Live Occupancy Report",
        "reports_history_label" to "Generated Occupancy Snapshots",
        "total_revenue" to "Total Smart Revenue",
        "active_res_count" to "Active Bookings",
        "active_vio_count" to "Unpaid Tickets",
        "generated_by" to "Report Officer",
        "empty_reports" to "No occupancy snapshots recorded yet. Tap generate to create one.",
        "empty_violations" to "Great clean campus! No active violations registered.",
        "empty_permits" to "No permits applied yet. Fill the quick form to issue one.",
        "empty_reservations" to "No active parking reservations found for this profile.",
        
        // Status types
        "NO_PERMIT" to "No Valid Permit",
        "OVERTIME" to "Overtime Parking",
        "WRONG_ZONE" to "Invalid Parking Zone",
        "STUDENT_SEMESTER" to "Student Semester",
        "STAFF_ANNUAL" to "Staff Annual",
        "VISITOR_DAILY" to "Visitor Daily Pass",
        "CREDIT_CARD" to "Credit Card",
        "APPLE_PAY" to "Apple Pay",
        "UNIV_ACCOUNT" to "University ID Wallet",
        "ACTIVE" to "Active",
        "COMPLETED" to "Completed",
        "EXPIRED" to "Expired"
    )

    private val arDict = mapOf(
        "app_title" to "هاب مواقف الجامعة",
        "app_subtitle" to "نظام ذكي متكامل لمراقبة وإدارة مواقف الحرم الجامعي",
        "role_user" to "طالب / موظف",
        "role_security" to "مكتب الأمن والسلامة",
        "select_lang" to "English",
        "active_user" to "ملف السائق النشط",
        "current_zone" to "المنطقة المحددة",
        "free_slots" to "المواقف الشاغرة",
        "total_slots" to "السعة الكلية",
        "reserve_now" to "احجز هذا الموقف",
        "reservation_title" to "حجز سريع لموقف",
        "select_vehicle" to "اختر المركبة",
        "input_vehicle_plate" to "أدخل رقم لوحة المركبة (مثال: ب ب ب ١٢٣٤)",
        "duration" to "المدة الزمنية",
        "hours" to "ساعة",
        "confirm_reservation" to "تأكيد واستكمال الحجز",
        "cancel" to "إلغاء",
        "active_reservations_label" to "حجوزاتك النشطة حالياً",
        "expiry_time" to "ينتهي الوقت في",
        "extend_time" to "تمديد الحجز",
        "payment_status" to "حالة السداد",
        "is_paid" to "تم الدفع",
        "unpaid" to "غير مدفوع (ادفع الآن)",
        "pay_now" to "سداد الرسوم",
        "permit_status" to "تصاريح مواقف الهاتف النشطة",
        "apply_permit" to "طلب تصريح موقف جديد",
        "vehicle_model" to "طراز ونوع المركبة",
        "permit_type" to "فترة التصريح المطلوبة",
        "permit_student" to "تصريح طالب فصل دراسي ($100)",
        "permit_staff" to "تصريح موظف سنوي ($200)",
        "permit_visitor" to "بطاقة زائر يومية ($10)",
        "register_and_apply" to "تسجيل المركبة وإصدار التصريح فوراً",
        "history_label" to "سجل العمليات والمدفوعات",
        "method" to "طريقة الدفع",
        "amount" to "المبلغ",
        "time" to "الوقت والمساء",
        "receipt" to "الفاتورة",
        
        // Security side
        "security_monitoring" to "نسبة إشغال مواقف الجامعة اللحظية",
        "occupancy_rate" to "مستوى إشغال النظام الحالي",
        "registered_violations" to "مخالفات المواقف المسجلة حالياً",
        "issue_violation" to "تحرير وإنشاء مخالفة وقوف",
        "violation_type" to "نوع وطبيعة المخالفة",
        "fine_amount" to "قيمة الغرامة المقررة",
        "location" to "موقع رصد المخالفة",
        "notes" to "ملاحظات وتوثيق الضبط",
        "issue_citation_btn" to "إصدار وتوثيق المخالفة",
        "violation_history" to "سجل مخالفات الحرم الجامعي",
        "verified_permits" to "سجل المصرح لهم بالوقوف",
        "check_in_out" to "بوابة تسجيل المركبات الإلكترونية",
        "license_plate_label" to "رقم لوحة المركبة",
        "check_in_btn" to "تسجيل دخول المركبة",
        "check_out_btn" to "تسجيل خروج (إخلاء الموقف)",
        "generate_report_btn" to "توليد تقرير إشغال حي فوري",
        "reports_history_label" to "سجلات تقارير الإشغال السابقة",
        "total_revenue" to "إجمالي الإيرادات الذكية",
        "active_res_count" to "الحجوزات النشطة",
        "active_vio_count" to "المخالفات النشطة",
        "generated_by" to "الضابط المسؤول",
        "empty_reports" to "لا يوجد أي تقارير إشغال مدرجة حتى الآن، انقر على توليد للحصول على الفوري",
        "empty_violations" to "الحرم الجامعي مثالي! لا يوجد أي مخالفات معلقة حالياً.",
        "empty_permits" to "لم يتم إصدار تصاريح بعد. املأ النموذج لإصدار تصريحك.",
        "empty_reservations" to "لا يوجد أي حجز موقف مسجل حالياً لملف هذا المستخدم.",
        
        // Status types
        "NO_PERMIT" to "عدم وجود تصريح صالح",
        "OVERTIME" to "تجاوز وقت الحجز المحدد",
        "WRONG_ZONE" to "الوقوف في منطقة غير مخصصة",
        "STUDENT_SEMESTER" to "طالب فصلي",
        "STAFF_ANNUAL" to "موظف سنوي",
        "VISITOR_DAILY" to "زائر يومي",
        "CREDIT_CARD" to "بطاقة ائتمان",
        "APPLE_PAY" to "أبل باي",
        "UNIV_ACCOUNT" to "محفظة الهوية الجامعية",
        "ACTIVE" to "نشط",
        "COMPLETED" to "منتهي ومغلق",
        "EXPIRED" to "منتهي الصلاحية"
    )
}
